import type { Task, User, Notification } from '../types';

export const MOCK_TASKS: Task[] = [
  {
    id: 't1',
    title: 'Design new dashboard UI',
    description: 'Create wireframes and high-fidelity mockups for the updated analytics dashboard.',
    priority: 'urgent',
    status: 'in_progress',
    category: 'work',
    due_date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    assigned_to: 'u2',
    created_by: 'u1',
    recurrence: 'none',
    tags: ['design', 'ui', 'dashboard'],
    progress: 60,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 't2',
    title: 'Implement JWT authentication',
    description: 'Set up JWT-based auth with refresh token rotation and bcrypt password hashing.',
    priority: 'high',
    status: 'completed',
    category: 'work',
    due_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    assigned_to: 'u3',
    created_by: 'u1',
    recurrence: 'none',
    tags: ['backend', 'security'],
    progress: 100,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 't3',
    title: 'Write unit tests for API',
    description: 'Cover all endpoints with Jest tests, aim for 80%+ coverage.',
    priority: 'medium',
    status: 'pending',
    category: 'work',
    due_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    assigned_to: 'u3',
    created_by: 'u2',
    recurrence: 'none',
    tags: ['testing', 'backend'],
    progress: 0,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 't4',
    title: 'Read Clean Architecture book',
    description: 'Read chapters 1-6 and take notes.',
    priority: 'low',
    status: 'in_progress',
    category: 'study',
    due_date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    assigned_to: 'u1',
    created_by: 'u1',
    recurrence: 'daily',
    tags: ['reading', 'architecture'],
    progress: 35,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 't5',
    title: 'Deploy to production',
    description: 'Finalize CI/CD pipeline and deploy the app to AWS.',
    priority: 'urgent',
    status: 'overdue',
    category: 'work',
    due_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    assigned_to: 'u2',
    created_by: 'u1',
    recurrence: 'none',
    dependencies: ['t2'],
    tags: ['devops', 'deployment'],
    progress: 25,
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 't6',
    title: 'Morning workout routine',
    description: '45-minute cardio + strength training.',
    priority: 'medium',
    status: 'completed',
    category: 'personal',
    due_date: new Date().toISOString(),
    assigned_to: 'u1',
    created_by: 'u1',
    recurrence: 'daily',
    tags: ['health', 'fitness'],
    progress: 100,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 't7',
    title: 'Kanban board drag & drop',
    description: 'Implement @dnd-kit for smooth task reordering across columns.',
    priority: 'high',
    status: 'pending',
    category: 'work',
    due_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    assigned_to: 'u3',
    created_by: 'u1',
    recurrence: 'none',
    tags: ['frontend', 'ux'],
    progress: 0,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 't8',
    title: 'Redux state management setup',
    description: 'Configure RTK slices for auth, tasks, and UI.',
    priority: 'high',
    status: 'completed',
    category: 'work',
    due_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    assigned_to: 'u2',
    created_by: 'u1',
    recurrence: 'none',
    tags: ['frontend', 'redux'],
    progress: 100,
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  { id: 'n1', title: 'Task Overdue', message: '"Deploy to production" is overdue!', type: 'error', read: false, createdAt: new Date().toISOString() },
  { id: 'n2', title: 'Task Completed', message: 'Jordan completed "Redux state management setup"', type: 'success', read: false, createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString() },
  { id: 'n3', title: 'Due Soon', message: '"Design new dashboard UI" is due tomorrow', type: 'warning', read: true, createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString() },
  { id: 'n4', title: 'New Assignment', message: 'You have been assigned a new task', type: 'info', read: true, createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString() },
];

export const WEEKLY_DATA = [
  { day: 'Mon', completed: 3, created: 5 },
  { day: 'Tue', completed: 5, created: 4 },
  { day: 'Wed', completed: 2, created: 6 },
  { day: 'Thu', completed: 7, created: 3 },
  { day: 'Fri', completed: 4, created: 5 },
  { day: 'Sat', completed: 1, created: 2 },
  { day: 'Sun', completed: 2, created: 1 },
];
